services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./storage:/var/www/storage
      - ./database:/var/www/database
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
